# Generated by Django 3.0.8 on 2020-09-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoulosProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('profile_image', models.ImageField(null=True, upload_to='staticfiles/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WomenStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='leaderprofile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='staticfiles/images/'),
        ),
        migrations.AlterField(
            model_name='leaderprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
